---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/git-commit: "c28a48e2e1e2de1e5daec7a2b6b09f9f8a3d4693"
    fabric8.io/iconUrl: "img/icons/spring-boot.svg"
    fabric8.io/git-branch: "master"
  labels:
    expose: "true"
    provider: "fabric8"
    project: "regulatory-soap-channel"
    version: "1.0.0-SNAPSHOT"
    group: "com.javainuse"
  name: "regulatory-soap-channel"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "regulatory-soap-channel"
    provider: "fabric8"
    group: "com.javainuse"
