---
apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  annotations:
    fabric8.io/git-commit: "c28a48e2e1e2de1e5daec7a2b6b09f9f8a3d4693"
    fabric8.io/iconUrl: "img/icons/spring-boot.svg"
    fabric8.io/git-branch: "master"
    fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=regulatory-soap-channel&var-version=1.0.0-SNAPSHOT"
  labels:
    provider: "fabric8"
    project: "regulatory-soap-channel"
    version: "1.0.0-SNAPSHOT"
    group: "com.javainuse"
  name: "regulatory-soap-channel"
spec:
  replicas: 1
  selector:
    project: "regulatory-soap-channel"
    provider: "fabric8"
    group: "com.javainuse"
  strategy:
    rollingParams:
      timeoutSeconds: 10800
    type: "Rolling"
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: "c28a48e2e1e2de1e5daec7a2b6b09f9f8a3d4693"
        fabric8.io/iconUrl: "img/icons/spring-boot.svg"
        fabric8.io/git-branch: "master"
        fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=regulatory-soap-channel&var-version=1.0.0-SNAPSHOT"
      labels:
        provider: "fabric8"
        project: "regulatory-soap-channel"
        version: "1.0.0-SNAPSHOT"
        group: "com.javainuse"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "javainuse/regulatory-soap-channel:snapshot-181106-142410-0611"
        imagePullPolicy: "IfNotPresent"
        name: "spring-boot"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        - containerPort: 9779
          name: "prometheus"
          protocol: "TCP"
        - containerPort: 8778
          name: "jolokia"
          protocol: "TCP"
        securityContext:
          privileged: false
  triggers:
  - type: "ConfigChange"
